OBJ = \
  startup.doj \
  main.doj \
  assert.doj \
  sport.doj \
  dma.doj \
  clocks.doj \
  timer.doj \
  pinmux.doj \
  uart.doj \
  printf.doj \
  twi.doj \
  mcp23017.doj \
  board.doj

CFLAGS_EXTRA += -DUSE_INTERNAL

include ../common/build.mk
