# SPDX-License-Identifier: MIT
# Makefile --- Build the sport_dma throughput benchmark for the ADSP-21569
# Copyright (c) 2026 Jakob Kastelic

OBJ = \
  startup.doj \
  main.doj \
  assert.doj \
  sport.doj \
  dma.doj \
  clocks.doj \
  timer.doj \
  pinmux.doj \
  uart.doj \
  printf.doj

include ../common/build.mk
