# SPDX-License-Identifier: MIT
# Makefile --- Build the SPI2 slave demo for the ADSP-21569
# Copyright (c) 2026 Jakob Kastelic

OBJ = \
  startup.doj \
  main.doj \
  clocks.doj \
  timer.doj \
  pinmux.doj \
  uart.doj \
  printf.doj \
  spi.doj

include ../common/build.mk
