# SPDX-License-Identifier: MIT
# Makefile --- Build the uart demo for the ADSP-21569
# Copyright (c) 2026 Jakob Kastelic

OBJ = \
  startup.doj \
  main.doj \
  clocks.doj \
  timer.doj \
  pinmux.doj \
  uart.doj \
  printf.doj \
  twi.doj \
  mcp23017.doj \
  board.doj \
  assert.doj

include ../common/build.mk
