# SPDX-License-Identifier: MIT
# Makefile --- sport_fpga_2x: SPORT0B + SPORT4B parallel PRBS receiver
# Copyright (c) 2026 Jakob Kastelic
OBJ = \
  startup.doj \
  main.doj \
  assert.doj \
  sport.doj \
  dma.doj \
  clocks.doj \
  gpio.doj \
  timer.doj \
  pinmux.doj \
  uart.doj \
  printf.doj \
  twi.doj \
  mcp23017.doj \
  board.doj

include ../common/build.mk
