OBJ = \
  startup.doj \
  main.doj \
  clocks.doj \
  timer.doj \
  pinmux.doj \
  uart.doj \
  printf.doj \
  twi.doj \
  mcp23017.doj \
  board.doj \
  iir.doj \
  assert.doj \
  runtime.doj

include ../common/build.mk
