# SPDX-License-Identifier: MIT
# Makefile --- sport_fpga_rx, single 4097-word variant
# Copyright (c) 2026 Jakob Kastelic
OBJ = \
  startup.doj \
  main.doj \
  assert.doj \
  sport.doj \
  gpio.doj \
  dma.doj \
  clocks.doj \
  timer.doj \
  pinmux.doj \
  uart.doj \
  printf.doj \
  twi.doj \
  mcp23017.doj \
  board.doj

include ../common/build.mk
