# SPDX-License-Identifier: MIT
# Makefile --- Build the SPI0 <-> SPI1 loopback demo
# Copyright (c) 2026 Jakob Kastelic

OBJ = \
  startup.doj \
  main.doj \
  assert.doj \
  clocks.doj \
  timer.doj \
  pinmux.doj \
  uart.doj \
  printf.doj \
  spi.doj \
  dma.doj \
  twi.doj \
  mcp23017.doj \
  board.doj

include ../common/build.mk
