# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Jakob Kastelic
OBJ = \
  startup.doj \
  main.doj \
  assert.doj \
  sport.doj \
  dma.doj \
  clocks.doj \
  timer.doj \
  pinmux.doj \
  gpio.doj \
  uart.doj \
  printf.doj \
  twi.doj \
  mcp23017.doj \
  board.doj

CFLAGS_EXTRA += -DRX_N=1U -DTX_N=1U

include ../common/build.mk
